### ISSUE TITLE
Java version check doesn't account for release numbers

### ISSUE THREAD

**Issue by anuraags** [koansys/koansys.recipe.elasticsearch#4]
I'm getting an error when using the elasticsearch recipe of:

```
Installing elasticsearch.
koansys.recipe.elasticsearch: found: java version "1.8.0_51"

While:
  Installing elasticsearch.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/zc/buildout/buildout.py", line 1992, in main
    getattr(buildout, command)(args)
  File "/Library/Python/2.7/site-packages/zc/buildout/buildout.py", line 666, in install
    installed_files = self[part]._call(recipe.install)
  File "/Library/Python/2.7/site-packages/zc/buildout/buildout.py", line 1407, in _call
    return f()
  File "/Users/asridhar/Development/Projects/mutant/eggs/koansys.recipe.elasticsearch-1.0.2-py2.7.egg/koansys/recipe/elasticsearch/__init__.py", line 176, in install
    return self.install_elasticsearch()
  File "/Users/asridhar/Development/Projects/mutant/eggs/koansys.recipe.elasticsearch-1.0.2-py2.7.egg/koansys/recipe/elasticsearch/__init__.py", line 56, in install_elasticsearch
    "Java 1.6 or higher ust be installed"
AssertionError: Java 1.6 or higher ust be installed
```

Looks like the regular expression used to verify the java version doesn't account for release numbers at the end.

This is on OS X by the way.

**Comment by mikejmets** [comment]
I had a similar problem with Ubuntu 14.04 but resolved it by using the master branch directly from github
